[2023-12-26T15:32:00.907-0300] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: TwitterDAG.twitter_transform_datascience scheduled__2023-12-20T00:00:00+00:00 [queued]>
[2023-12-26T15:32:00.912-0300] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: TwitterDAG.twitter_transform_datascience scheduled__2023-12-20T00:00:00+00:00 [queued]>
[2023-12-26T15:32:00.912-0300] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-12-26T15:32:00.927-0300] {taskinstance.py:1382} INFO - Executing <Task(SparkSubmitOperator): twitter_transform_datascience> on 2023-12-20 00:00:00+00:00
[2023-12-26T15:32:00.929-0300] {standard_task_runner.py:57} INFO - Started process 8326 to run task
[2023-12-26T15:32:00.931-0300] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'TwitterDAG', 'twitter_transform_datascience', 'scheduled__2023-12-20T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/twitter_dag.py', '--cfg-path', '/tmp/tmpomszd46j']
[2023-12-26T15:32:00.932-0300] {standard_task_runner.py:85} INFO - Job 11: Subtask twitter_transform_datascience
[2023-12-26T15:32:00.963-0300] {task_command.py:416} INFO - Running <TaskInstance: TwitterDAG.twitter_transform_datascience scheduled__2023-12-20T00:00:00+00:00 [running]> on host MI0118G-ATIC.gabaer.intraer
[2023-12-26T15:32:01.079-0300] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='TwitterDAG' AIRFLOW_CTX_TASK_ID='twitter_transform_datascience' AIRFLOW_CTX_EXECUTION_DATE='2023-12-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-20T00:00:00+00:00'
[2023-12-26T15:32:01.081-0300] {base.py:73} INFO - Using connection ID 'spark_default' for task execution.
[2023-12-26T15:32:01.083-0300] {spark_submit.py:351} INFO - Spark-Submit cmd: spark-submit --master yarn --name twitter_transformation --queue root.default /home/pedro/projetos/projetos_python/proj_twitter_pipeline/src/spark/transformation.py --origem /home/pedro/projetos/projetos_python/proj_twitter_pipeline/datalake/bronze/twitter_datascience/extract_date=2023-12-20 --destino /home/pedro/projetos/projetos_python/proj_twitter_pipeline/datalake/silver/twitter_datascience/ --process_date 2023-12-20
[2023-12-26T15:32:02.843-0300] {spark_submit.py:521} INFO - 23/12/26 15:32:02 WARN Utils: Your hostname, MI0118G-ATIC resolves to a loopback address: 127.0.1.1; using 172.21.232.236 instead (on interface eth0)
[2023-12-26T15:32:02.844-0300] {spark_submit.py:521} INFO - 23/12/26 15:32:02 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
[2023-12-26T15:32:02.884-0300] {spark_submit.py:521} INFO - Exception in thread "main" org.apache.spark.SparkException: When running with master 'yarn' either HADOOP_CONF_DIR or YARN_CONF_DIR must be set in the environment.
[2023-12-26T15:32:02.885-0300] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmitArguments.error(SparkSubmitArguments.scala:634)
[2023-12-26T15:32:02.885-0300] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateSubmitArguments(SparkSubmitArguments.scala:274)
[2023-12-26T15:32:02.885-0300] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateArguments(SparkSubmitArguments.scala:234)
[2023-12-26T15:32:02.885-0300] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:119)
[2023-12-26T15:32:02.885-0300] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:1037)
[2023-12-26T15:32:02.885-0300] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:1037)
[2023-12-26T15:32:02.885-0300] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:85)
[2023-12-26T15:32:02.885-0300] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1054)
[2023-12-26T15:32:02.885-0300] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1063)
[2023-12-26T15:32:02.885-0300] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2023-12-26T15:32:02.895-0300] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/pedro/projetos/projetos_python/proj_twitter_pipeline/venv/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 160, in execute
    self._hook.submit(self._application)
  File "/home/pedro/projetos/projetos_python/proj_twitter_pipeline/venv/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 452, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --name twitter_transformation --queue root.default /home/pedro/projetos/projetos_python/proj_twitter_pipeline/src/spark/transformation.py --origem /home/pedro/projetos/projetos_python/proj_twitter_pipeline/datalake/bronze/twitter_datascience/extract_date=2023-12-20 --destino /home/pedro/projetos/projetos_python/proj_twitter_pipeline/datalake/silver/twitter_datascience/ --process_date 2023-12-20. Error code is: 1.
[2023-12-26T15:32:02.897-0300] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=TwitterDAG, task_id=twitter_transform_datascience, execution_date=20231220T000000, start_date=20231226T183200, end_date=20231226T183202
[2023-12-26T15:32:02.912-0300] {standard_task_runner.py:104} ERROR - Failed to execute job 11 for task twitter_transform_datascience (Cannot execute: spark-submit --master yarn --name twitter_transformation --queue root.default /home/pedro/projetos/projetos_python/proj_twitter_pipeline/src/spark/transformation.py --origem /home/pedro/projetos/projetos_python/proj_twitter_pipeline/datalake/bronze/twitter_datascience/extract_date=2023-12-20 --destino /home/pedro/projetos/projetos_python/proj_twitter_pipeline/datalake/silver/twitter_datascience/ --process_date 2023-12-20. Error code is: 1.; 8326)
[2023-12-26T15:32:02.952-0300] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-26T15:32:02.971-0300] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-12-26T15:40:24.254-0300] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: TwitterDAG.twitter_transform_datascience scheduled__2023-12-20T00:00:00+00:00 [queued]>
[2023-12-26T15:40:24.260-0300] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: TwitterDAG.twitter_transform_datascience scheduled__2023-12-20T00:00:00+00:00 [queued]>
[2023-12-26T15:40:24.260-0300] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-12-26T15:40:24.276-0300] {taskinstance.py:1382} INFO - Executing <Task(SparkSubmitOperator): twitter_transform_datascience> on 2023-12-20 00:00:00+00:00
[2023-12-26T15:40:24.279-0300] {standard_task_runner.py:57} INFO - Started process 11767 to run task
[2023-12-26T15:40:24.282-0300] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'TwitterDAG', 'twitter_transform_datascience', 'scheduled__2023-12-20T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/twitter_dag.py', '--cfg-path', '/tmp/tmpptpyno56']
[2023-12-26T15:40:24.283-0300] {standard_task_runner.py:85} INFO - Job 11: Subtask twitter_transform_datascience
[2023-12-26T15:40:24.316-0300] {task_command.py:416} INFO - Running <TaskInstance: TwitterDAG.twitter_transform_datascience scheduled__2023-12-20T00:00:00+00:00 [running]> on host MI0118G-ATIC.gabaer.intraer
[2023-12-26T15:40:24.450-0300] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='TwitterDAG' AIRFLOW_CTX_TASK_ID='twitter_transform_datascience' AIRFLOW_CTX_EXECUTION_DATE='2023-12-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-20T00:00:00+00:00'
[2023-12-26T15:40:24.453-0300] {base.py:73} INFO - Using connection ID 'spark_default' for task execution.
[2023-12-26T15:40:24.454-0300] {spark_submit.py:351} INFO - Spark-Submit cmd: spark-submit --master yarn --name twitter_transformation --queue root.default /home/pedro/projetos/projetos_python/proj_twitter_pipeline/src/spark/transformation.py --origem /home/pedro/projetos/projetos_python/proj_twitter_pipeline/datalake/bronze/twitter_datascience/extract_date=2023-12-20 --destino /home/pedro/projetos/projetos_python/proj_twitter_pipeline/datalake/silver/twitter_datascience/ --process_date 2023-12-20
[2023-12-26T15:40:25.354-0300] {spark_submit.py:521} INFO - 23/12/26 15:40:25 WARN Utils: Your hostname, MI0118G-ATIC resolves to a loopback address: 127.0.1.1; using 172.21.232.236 instead (on interface eth0)
[2023-12-26T15:40:25.354-0300] {spark_submit.py:521} INFO - 23/12/26 15:40:25 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
[2023-12-26T15:40:25.396-0300] {spark_submit.py:521} INFO - Exception in thread "main" org.apache.spark.SparkException: When running with master 'yarn' either HADOOP_CONF_DIR or YARN_CONF_DIR must be set in the environment.
[2023-12-26T15:40:25.397-0300] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmitArguments.error(SparkSubmitArguments.scala:634)
[2023-12-26T15:40:25.397-0300] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateSubmitArguments(SparkSubmitArguments.scala:274)
[2023-12-26T15:40:25.397-0300] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateArguments(SparkSubmitArguments.scala:234)
[2023-12-26T15:40:25.397-0300] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:119)
[2023-12-26T15:40:25.398-0300] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:1037)
[2023-12-26T15:40:25.398-0300] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:1037)
[2023-12-26T15:40:25.398-0300] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:85)
[2023-12-26T15:40:25.398-0300] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1054)
[2023-12-26T15:40:25.398-0300] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1063)
[2023-12-26T15:40:25.398-0300] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2023-12-26T15:40:25.409-0300] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/pedro/projetos/projetos_python/proj_twitter_pipeline/venv/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 160, in execute
    self._hook.submit(self._application)
  File "/home/pedro/projetos/projetos_python/proj_twitter_pipeline/venv/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 452, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --name twitter_transformation --queue root.default /home/pedro/projetos/projetos_python/proj_twitter_pipeline/src/spark/transformation.py --origem /home/pedro/projetos/projetos_python/proj_twitter_pipeline/datalake/bronze/twitter_datascience/extract_date=2023-12-20 --destino /home/pedro/projetos/projetos_python/proj_twitter_pipeline/datalake/silver/twitter_datascience/ --process_date 2023-12-20. Error code is: 1.
[2023-12-26T15:40:25.411-0300] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=TwitterDAG, task_id=twitter_transform_datascience, execution_date=20231220T000000, start_date=20231226T184024, end_date=20231226T184025
[2023-12-26T15:40:25.423-0300] {standard_task_runner.py:104} ERROR - Failed to execute job 11 for task twitter_transform_datascience (Cannot execute: spark-submit --master yarn --name twitter_transformation --queue root.default /home/pedro/projetos/projetos_python/proj_twitter_pipeline/src/spark/transformation.py --origem /home/pedro/projetos/projetos_python/proj_twitter_pipeline/datalake/bronze/twitter_datascience/extract_date=2023-12-20 --destino /home/pedro/projetos/projetos_python/proj_twitter_pipeline/datalake/silver/twitter_datascience/ --process_date 2023-12-20. Error code is: 1.; 11767)
[2023-12-26T15:40:25.464-0300] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-26T15:40:25.494-0300] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
